### ISSUE TITLE
Depreciation warning "CoreInterfaces\Core\Response\ResponseInterface::getBody() might add mixed"

### ISSUE THREAD

**Issue by stanislav-oop** [apimatic/unirest-php#50]
Please add : mixed to apimatic\unirest-php\src\Response.php

   " public function getBody(): mixed"

Otherwise I am getting depreciation warnings:

 1x: Method "CoreInterfaces\Core\Response\ResponseInterface::getBody()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Unirest\Response" now to avoid errors or add an explicit @return annotation to suppress this message.

Thank you

**Comment by asadali214** [comment]
Thank you @stanislav-oop for submitting this issue, the `mixed` type was only [introduced in PHP 8.0](https://www.php.net/manual/en/language.types.mixed.php) and above.

We also intend to support `PHP 7.2` as the minimum version for `unirest-php` which is why we can not add the `mixed` return type here.

Please ignore this Depreciation warning "CoreInterfaces\Core\Response\ResponseInterface::getBody() might add mixed"

**Comment by stanislav-oop** [comment]
Thank you for your reply! There can be another solution to that: remove  on a parent or add in Response class this:
    /**
     * @return mixed
     */

**Comment by asadali214** [comment]
@stanislav-oop That's a good suggestion. We have noted it down, will be making this change a part of our upcoming release!

**Comment by asadali214** [comment]
Hey @stanislav-oop we have released this fix via the release of `core-interfaces-php`: https://github.com/apimatic/core-interfaces-php/releases/tag/0.1.3
